=== SamPenrose/mozilla-pipeline-schemas/schemas/pioneer-sgsb-beyond-the-paywall/advertisement/advertisement.1.schema.json
{
  "$comment": "Please do not edit this schema by hand. Generate it instead by running npm run build:schema.",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "mozPipelineMetadata": {
    "bq_dataset_family": "pioneer_sgsb_beyond_the_paywall",
    "bq_metadata_format": "pioneer",
    "bq_table": "advertisement_v1",
    "expiration_policy": {
      "collect_through_date": "2022-12-31"
    }
  },
  "properties": {
    "ads": {
      "description": "This array contains an object per advertisement found",
      "items": {
        "properties": {
          "clientHeight": {
            "description": "The calculated height of the ad HTML element in pixels",
            "type": [
              "integer",
              "null"
            ]
          },
          "clientWidth": {
            "description": "The calculated width of the ad HTML element in pixels",
            "type": [
              "integer",
              "null"
            ]
          },
          "height": {
            "description": "The height of the HTML element, as listed in it's style attributes",
            "type": [
              "string",
              "null"
            ]
          },
          "id": {
            "description": "The ID of the ad, if listed in the HTML element",
            "type": [
              "string",
              "null"
            ]
          },
          "tag": {
            "description": "The HTML tag type that the ad was in",
            "type": [
              "string",
              "null"
            ]
          },
          "width": {
            "description": "The width of the HTML element, as listed in it's style attributes",
            "type": [
              "string",
              "null"
            ]
          }
        },
        "type": "object"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "body": {
      "description": "This object contains two properties listed below about the <body> tag of the page.  This is needed to normalize the size of advertisments against full page size.",
      "properties": {
        "clientHeight": {
          "description": "The calculated height in pixels of the <body> tag",
          "type": [
            "integer",
            "null"
          ]
        },
        "clientWidth": {
          "description": "The calculated width in pixels of the <body> tag",
          "type": [
            "integer",
            "null"
          ]
        }
      },
      "type": "object"
    },
    "tabId": {
      "description": "The ID of the tab this data was collected from",
      "type": [
        "integer",
        "null"
      ]
    },
    "type": {
      "description": "the type of event recorded. Either WebScience.advertisements, WebScience.articleContents, WebScience.pageNav, or WebScience.pageNavSensitive",
      "enum": [
        "WebScience.advertisements",
        "WebScience.articleContents",
        "WebScience.pageNav",
        "WebScience.pageNavSensitive",
        "WebScience.totalTiming"
      ],
      "type": "string"
    },
    "url": {
      "description": "The URL of the page visited",
      "type": [
        "string",
        "null"
      ]
    },
    "userId": {
      "description": "a unique ID associated with a participant.",
      "type": "string"
    },
    "visitId": {
      "description": "a unique ID associated with a page visit.",
      "type": "string"
    }
  },
  "required": [
    "type",
    "visitId",
    "userId",
    "body"
  ],
  "type": "object"
}

=== SamPenrose/mozilla-pipeline-schemas/validation/rally-beyond-the-paywall/1.iii.advertisements.pass.json
{
      "type": "WebScience.advertisements",
      "userId": "b4aeab86-1535-4701-8a20-a9aab64e0866",
      "visitId": "6743f613-4c9d-4c22-af21-28db956faac2",
      "url": "https://www.latimes.com/entertainment-arts/tv/story/2021-06-08/chris-harrison-the-bachelor-exit-matt-james-rachael-kirkconnell",
      "body": {
        "clientHeight": 7293,
        "clientWidth": 1316
      },
      "ads": [
        {
          "id": "google_ads_iframe_/21787098806/web.latimes/entertainment-arts/television_0",
          "tag": "IFRAME",
          "clientHeight": 90,
          "clientWidth": 728,
          "height": "90",
          "width": "728"
        }
      ]
  }

=== SamPenrose/mozilla-pipeline-schemas/validation/pioneer-sgsb-beyond-the-paywall/advertisement.1.1i.pass.json
{
      "type": "WebScience.advertisements",
      "userId": "b4aeab86-1535-4701-8a20-a9aab64e0866",
      "visitId": "e44f4b1b-91b1-4a5f-ac22-82346d37c44a",
      "url": "https://www.nytimes.com/2021/06/08/us/politics/capitol-riot-security.html",
      "body": {
        "clientHeight": 983,
        "clientWidth": 1265
      },
      "ads": [
        {
          "id": "bottom",
          "tag": "DIV",
          "clientHeight": 90,
          "clientWidth": 1265
        },
        {
          "id": "google_ads_iframe_/29390238/nyt/us/politics_0",
          "tag": "IFRAME",
          "clientHeight": 250,
          "clientWidth": 970,
          "height": "250",
          "width": "970"
        },
        {
          "id": "",
          "tag": "IFRAME",
          "clientHeight": 1,
          "clientWidth": 1,
          "height": "",
          "width": ""
        }
      ]
  }

=== SamPenrose/mozilla-pipeline-schemas/validation/rally-beyond-the-paywall/1.ii.advertisements.pass.json
{
      "type": "WebScience.advertisements",
      "userId": "b4aeab86-1535-4701-8a20-a9aab64e0866",
      "visitId": "475f342e-200f-4f74-b2cf-0ec9a89da19b",
      "url": "https://www.mercurynews.com/2021/06/08/under-the-wire-two-bay-area-counties-could-reach-yellow-tier-in-its-final-week/",
      "body": {
        "clientHeight": 3789,
        "clientWidth": 1316
      },
      "ads": []
  }
