=== SamPenrose/mozilla-pipeline-schemas/schemas/messaging-system/onboarding/onboarding.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "mozPipelineMetadata": {
    "bq_dataset_family": "messaging_system",
    "bq_metadata_format": "structured",
    "bq_table": "onboarding_v1",
    "expiration_policy": {
      "delete_after_days": 180
    },
    "sample_id_source_uuid_attribute": "client_id",
    "sample_id_source_uuid_payload_path": [
      "impression_id"
    ]
  },
  "properties": {
    "addon_version": {
      "type": "string"
    },
    "attribution": {
      "properties": {
        "campaign": {
          "description": "Identifier of the particular campaign that led to the download of the product.",
          "type": [
            "string",
            "null"
          ]
        },
        "content": {
          "description": "Identifier to indicate the particular link within a campaign.",
          "type": [
            "string",
            "null"
          ]
        },
        "dlsource": {
          "description": "Identifier that indicates where installations of Firefox originate, see bug 1827238",
          "type": [
            "string",
            "null"
          ]
        },
        "dltoken": {
          "description": "Unique token created at Firefox download time, see bug 1757451",
          "type": [
            "string",
            "null"
          ]
        },
        "experiment": {
          "description": "Funnel experiment parameters, see bug 1567339",
          "type": [
            "string",
            "null"
          ]
        },
        "medium": {
          "description": "Category of the source, such as 'organic' for a search engine.",
          "type": [
            "string",
            "null"
          ]
        },
        "source": {
          "description": "Referring partner domain, when install happens via a known partner.",
          "type": [
            "string",
            "null"
          ]
        },
        "ua": {
          "description": "Derived user agent, see bug 1595063",
          "type": [
            "string",
            "null"
          ]
        },
        "variation": {
          "description": "Funnel experiment parameters, see bug 1567339",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "browser_session_id": {
      "description": "A mirror of the browser sessionId, as defined in https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/main/schemas/telemetry/main/main.4.schema.json",
      "type": [
        "string",
        "null"
      ]
    },
    "client_id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "event": {
      "description": "An event identifier",
      "type": "string"
    },
    "event_context": {
      "description": "A string that describes the context about this event",
      "type": [
        "string",
        "null"
      ]
    },
    "experiments": {
      "additionalProperties": {
        "properties": {
          "branch": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "description": "An object to record all active experiments, experiments IDs are stored as keys, and the value object stores the branch information. Example: {\"experiment_1\": {\"branch\": \"control\"}, \"experiment_2\": {\"branch\": \"treatment\"}}. This deprecates the \"shield_id\" used in activity-stream and messaging-system.",
      "type": [
        "object",
        "null"
      ]
    },
    "locale": {
      "type": "string"
    },
    "message_id": {
      "type": "string"
    },
    "profile_creation_date": {
      "type": [
        "integer",
        "null"
      ]
    },
    "release_channel": {
      "type": [
        "string",
        "null"
      ]
    },
    "shield_id": {
      "description": "[DEPRECATED]: use `experiments` instead. A semicolon separated string to store a list of Shield study IDs",
      "type": [
        "string",
        "null"
      ]
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "client_id",
    "event",
    "message_id",
    "addon_version",
    "version",
    "locale"
  ],
  "title": "onboarding",
  "type": "object"
}

=== SamPenrose/mozilla-pipeline-schemas/validation/messaging-system/infobar.1.event.pass.json
{
  "experiments": {
    "exp1": {
      "branch": "treatment-a"
    }
  },
  "addon_version": "20210115035053",
  "release_channel": "release",
  "locale": "en-US",
  "event": "IMPRESSION",
  "client_id": "c4beb4bf-4feb-9c4e-9587-9323b28c2e50",
  "version": "86",
  "message_id": "INFOBAR_ACTION_86",
  "browser_session_id": "93714e76-9919-ca49-b697-5e7c09a1394f"
}
