=== SamPenrose/mozilla-pipeline-schemas/schemas/telemetry/account-ecosystem/account-ecosystem.4.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "mozPipelineMetadata": {
    "bq_dataset_family": "telemetry",
    "bq_metadata_format": "telemetry",
    "bq_table": "account_ecosystem_v4",
    "jwe_mappings": [
      {
        "decrypted_field_path": "payload.ecosystemUserId",
        "source_field_path": "payload.ecosystemAnonId"
      },
      {
        "decrypted_field_path": "payload.previousEcosystemUserIds",
        "source_field_path": "payload.previousEcosystemAnonIds"
      }
    ]
  },
  "properties": {
    "application": {
      "additionalProperties": false,
      "properties": {
        "architecture": {
          "type": "string"
        },
        "buildId": {
          "pattern": "^[0-9]{10}",
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "displayVersion": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "platformVersion": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "vendor": {
          "type": "string"
        },
        "version": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "xpcomAbi": {
          "type": "string"
        }
      },
      "required": [
        "architecture",
        "buildId",
        "channel",
        "name",
        "platformVersion",
        "version",
        "vendor",
        "xpcomAbi"
      ],
      "type": "object"
    },
    "creationDate": {
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
      "type": "string"
    },
    "environment": {
      "properties": {
        "profile": {
          "properties": {
            "creationDate": {
              "type": "number"
            },
            "firstUseDate": {
              "type": "number"
            }
          },
          "required": [
            "creationDate"
          ],
          "type": "object"
        },
        "settings": {
          "properties": {
            "locale": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "locale"
          ],
          "type": "object"
        },
        "system": {
          "properties": {
            "cpu": {
              "properties": {
                "speedMHz": {
                  "type": [
                    "number",
                    "null"
                  ]
                }
              },
              "required": [
                "speedMHz"
              ],
              "type": "object"
            },
            "memoryMB": {
              "type": [
                "number",
                "null"
              ]
            },
            "os": {
              "properties": {
                "locale": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "name": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "version": {
                  "type": [
                    "string",
                    "null"
                  ]
                }
              },
              "required": [
                "name",
                "version",
                "locale"
              ],
              "type": "object"
            }
          },
          "required": [
            "memoryMB",
            "cpu",
            "os"
          ],
          "type": "object"
        }
      },
      "required": [
        "settings",
        "system",
        "profile"
      ],
      "type": "object"
    },
    "id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "payload": {
      "properties": {
        "duration": {
          "type": "integer"
        },
        "ecosystemClientId": {
          "type": "string"
        },
        "ecosystemUserId": {
          "description": "Account Ecosystem Telemetry user identifier; this value is not present in the original payload sent by clients, but is instead inserted by the pipeline after decrypting and removing ecosystemAnonId",
          "pattern": "[a-zA-z0-9]{64}",
          "type": "string"
        },
        "histograms": {
          "properties": {
            "parent": {
              "additionalProperties": {
                "type": [
                  "integer",
                  "string",
                  "boolean"
                ]
              },
              "type": "object"
            }
          },
          "type": "object"
        },
        "keyedHistograms": {
          "properties": {
            "parent": {
              "additionalProperties": {
                "additionalProperties": {
                  "additionalProperties": false,
                  "properties": {
                    "bucket_count": {
                      "minimum": 0,
                      "type": "integer"
                    },
                    "histogram_type": {
                      "minimum": 0,
                      "type": "integer"
                    },
                    "log_sum": {
                      "minimum": 0,
                      "type": "number"
                    },
                    "log_sum_squares": {
                      "minimum": 0,
                      "type": "number"
                    },
                    "range": {
                      "items": {
                        "type": "integer"
                      },
                      "type": "array"
                    },
                    "sum": {
                      "minimum": 0,
                      "type": "integer"
                    },
                    "sum_squares_hi": {
                      "minimum": 0,
                      "type": "integer"
                    },
                    "sum_squares_lo": {
                      "minimum": 0,
                      "type": "integer"
                    },
                    "values": {
                      "additionalProperties": false,
                      "patternProperties": {
                        "^[0-9]+$": {
                          "minimum": 0,
                          "type": "integer"
                        }
                      },
                      "type": "object"
                    }
                  },
                  "type": "object"
                },
                "type": "object"
              },
              "type": "object"
            }
          },
          "type": "object"
        },
        "keyedScalars": {
          "properties": {
            "parent": {
              "additionalProperties": {
                "additionalProperties": {
                  "type": [
                    "integer",
                    "string",
                    "boolean"
                  ]
                },
                "type": "object"
              }
            }
          },
          "type": "object"
        },
        "previousEcosystemUserIds": {
          "description": "Previous Account Ecosystem Telemetry identifiers associated with this user; this value is not present in the original payload sent by clients, but is instead inserted by the pipeline after decrypting and removing previousEcosystemAnonIds",
          "items": {
            "pattern": "[a-zA-z0-9]{64}",
            "type": "string"
          },
          "type": "array"
        },
        "reason": {
          "type": "string"
        },
        "scalars": {
          "properties": {
            "parent": {
              "additionalProperties": {
                "type": [
                  "integer",
                  "string",
                  "boolean"
                ]
              },
              "type": "object"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "ecosystemClientId"
      ],
      "type": "object"
    },
    "type": {
      "enum": [
        "account-ecosystem"
      ],
      "type": "string"
    },
    "version": {
      "maximum": 4,
      "minimum": 4,
      "type": "number"
    }
  },
  "required": [
    "application",
    "creationDate",
    "id",
    "type",
    "version",
    "payload"
  ],
  "title": "account-ecosystem",
  "type": "object"
}

=== SamPenrose/mozilla-pipeline-schemas/validation/telemetry/account-ecosystem.4.sample.pass.json
{
  "type": "account-ecosystem",
  "id": "2aac7cec-0b1d-ac42-a369-610223b786a4",
  "creationDate": "2019-03-13T10:41:04.858Z",
  "version": 4,
  "application": {
    "architecture": "x86-64",
    "buildId": "20190227201333",
    "name": "Firefox",
    "version": "67.0a1",
    "displayVersion": "67.0a1",
    "vendor": "Mozilla",
    "platformVersion": "67.0a1",
    "xpcomAbi": "x86_64-gcc3",
    "channel": "default"
  },
  "payload": {
    "ecosystemClientId": "5bdc7cec-0b1d-ac42-a369-610223b7869d",
    "ecosystemUserId": "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh",
    "previousEcosystemUserIds": ["18cdefghabcdefghabcdefghabcdefgh1bcdefghabcdefghabcdefghabcdefg3"],
    "duration": 8547,
    "scalars": {
      "parent": {
        "browser.engagement.active_ticks": 12,
        "browser.engagement.total_uri_count": 3
      }
    },
    "keyedScalars": {
      "key1": 12,
      "key2": "foo"
    },
    "histograms": {
      "content": {},
      "dynamic": {},
      "extension": {},
      "gpu": {},
      "parent": {},
      "socket": {}
    },
    "keyedHistograms": {
      "content": {},
      "dynamic": {},
      "extension": {},
      "gpu": {},
      "parent": {
        "SEARCH_COUNTS": {
          "google.in-content:sap:firefox-b-d": {
            "bucket_count": 3,
            "histogram_type": 4,
            "sum": 1,
            "range": [
              1,
              2
            ],
            "values": {
              "0": 1,
              "1": 0
            }
          },
          "google-b-d.urlbar": {
            "bucket_count": 3,
            "histogram_type": 4,
            "sum": 1,
            "range": [
              1,
              2
            ],
            "values": {
              "0": 1,
              "1": 0
            }
          }
        }
      },
      "socket": {}
    }
  }
}
