=== SamPenrose/mozilla-pipeline-schemas/schemas/pioneer-core/demographic-survey/demographic-survey.1.schema.json
{
  "$comment": "mozilla-ion/ion-core-addon#182 - Collect demographic information",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "mozPipelineMetadata": {
    "bq_dataset_family": "pioneer_core",
    "bq_metadata_format": "pioneer",
    "bq_table": "demographic_survey_v1",
    "expiration_policy": {
      "collect_through_date": "2023-03-27"
    }
  },
  "properties": {
    "age": {
      "additionalProperties": false,
      "properties": {
        "19_24": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "25_34": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "35_44": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "45_54": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "55_64": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "over_65": {
          "type": [
            "boolean",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "education": {
      "additionalProperties": false,
      "properties": {
        "associates_degree": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "bachelors_degree": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "graduate_degree": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "high_school_graduate_or_equivalent": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "less_than_high_school": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "some_college_but_no_degree_or_in_progress": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "some_high_school": {
          "type": [
            "boolean",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "exactIncome": {
      "description": "https://github.com/mozilla-rally/rally-core-addon/pull/624 - new exactIncome field for Rally Core Add-On demographic survey",
      "type": [
        "number",
        "null"
      ]
    },
    "gender": {
      "additionalProperties": false,
      "properties": {
        "decline": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "female": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "male": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "neither": {
          "type": [
            "boolean",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "income": {
      "additionalProperties": false,
      "description": "this field has been deprecated in favor of exactIncome",
      "properties": {
        "0_24999": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "100000_149999": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "25000_49999": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "50000_74999": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "75000_99999": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "ge_150000": {
          "type": [
            "boolean",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "origin": {
      "additionalProperties": false,
      "properties": {
        "hispanicLatinoSpanish": {
          "description": "This field is deprecated in favour of hispanicLatinxSpanish",
          "type": [
            "boolean",
            "null"
          ]
        },
        "hispanicLatinxSpanish": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "other": {
          "type": [
            "boolean",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "races": {
      "additionalProperties": false,
      "properties": {
        "american_indian_or_alaska_native": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "asian_indian": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "black_or_african_american": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "chamorro": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "chinese": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "filipino": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "japanese": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "korean": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "native_hawaiian": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "other_asian": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "other_pacific_islander": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "samoan": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "some_other_race": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "vietnamese": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "white": {
          "type": [
            "boolean",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "zipCode": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "title": "demographic-survey",
  "type": "object"
}

=== SamPenrose/mozilla-pipeline-schemas/validation/pioneer-core/demographic-survey.1.full.pass.json
{
    "age": {
        "25_34": true
    },
    "gender": {
        "decline": true
    },
    "origin": {
        "other": true
    },
    "education": {
        "high_school_graduate_or_equivalent": true
    },
    "income": {
        "25000_49999": true
    },
    "races": {
        "black_or_african_american": true,
        "native_hawaiian": true
    }
}

=== SamPenrose/mozilla-pipeline-schemas/validation/pioneer-core/demographic-survey.1.deprecated-income-range.pass.json
{
  "age": {
    "25_34": true
  },
  "origin": {
    "other": true
  },
  "education": {
    "high_school_graduate_or_equivalent": true
  },
  "gender": {
    "decline": true
  },
  "income": {
    "25000_49999": true
  },
  "races": {
    "black_or_african_american": true,
    "native_hawaiian": true
  }
}
