=== SamPenrose/mozilla-pipeline-schemas/schemas/pioneer-citp-news-disinfo-two/measurements/measurements.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "mozPipelineMetadata": {
    "bq_dataset_family": "pioneer_citp_news_disinfo_two",
    "bq_metadata_format": "pioneer",
    "bq_table": "measurements_v1",
    "expiration_policy": {
      "collect_through_date": "2022-12-31",
      "delete_after_days": 180
    }
  },
  "properties": {
    "WebScience.Measurements.LinkExposure": {
      "additionalProperties": false,
      "properties": {
        "linkExposures": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "dayOfWeek": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "destinationDomain": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "laterSharedCount": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "laterVisitedCount": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "numExposures": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "sourceDomain": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "timeOfDay": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "visThreshold": {
                "type": [
                  "integer",
                  "null"
                ]
              }
            },
            "type": "object"
          },
          "type": [
            "array",
            "null"
          ]
        },
        "untrackedLinkExposures": {
          "additionalProperties": {
            "type": "integer"
          },
          "propertyNames": {
            "pattern": "^[0-9]*$"
          },
          "type": [
            "object",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "WebScience.Measurements.PageNavigation": {
      "additionalProperties": false,
      "properties": {
        "numUntrackedVisits": {
          "type": [
            "integer",
            "null"
          ]
        },
        "trackedVisitsByDomain": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "domain": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "numSessions": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "visitsByReferrer": {
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "classifierResults": {
                      "additionalProperties": {
                        "type": "integer"
                      },
                      "description": "additional properties are the name of the classifier, with the classification result as the value",
                      "type": [
                        "object",
                        "null"
                      ]
                    },
                    "dayOfWeek": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "laterSharedCount": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "numVisits": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "pageCategory": {
                      "description": "deprecated, use classifierResults",
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "prevExposedCount": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "referrerDomain": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "timeOfDay": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "totalAttention": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "totalScroll": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    }
                  },
                  "type": "object"
                },
                "type": [
                  "array",
                  "null"
                ]
              }
            },
            "type": "object"
          },
          "type": [
            "array",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "WebScience.Measurements.SocialMediaLinkSharing": {
      "additionalProperties": false,
      "properties": {
        "linkSharesByPlatform": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "numUntrackedShares": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "platform": {
                "enum": [
                  "facebook",
                  "twitter",
                  "reddit",
                  null
                ],
                "type": [
                  "string",
                  "null"
                ]
              },
              "trackedShares": {
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "audience": {
                      "enum": [
                        "public",
                        "restricted",
                        "unknown",
                        null
                      ],
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "classification": {
                      "description": "deprecated, use classifierResults",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "classifierResults": {
                      "additionalProperties": {
                        "type": "integer"
                      },
                      "description": "additional properties are the name of the classifier, with the classification result as the value",
                      "type": [
                        "object",
                        "null"
                      ]
                    },
                    "dayOfWeek": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "domain": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "numShares": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "pageClassification": {
                      "description": "deprecated, use classifierResults",
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "prevExposed": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "source": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "timeOfDay": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "visitReferrer": {
                      "type": [
                        "string",
                        "null"
                      ]
                    }
                  },
                  "type": "object"
                },
                "type": [
                  "array",
                  "null"
                ]
              }
            },
            "type": "object"
          },
          "type": [
            "array",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "WebScience.SurveyId": {
      "description": "ID sent to Qualtrics, for associating survey responses with telemetry data",
      "type": [
        "string",
        "null"
      ]
    },
    "WebScience.version": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "type": "object"
}

=== SamPenrose/mozilla-pipeline-schemas/validation/pioneer-citp-news-disinfo/measurements.1.sample.pass.json
{
  "WebScience.SurveyId": "f85b22d6-b0a6-419f-820a-75f28c1a8af3",
  "WebScience.Measurements.PageNavigation": {
    "numUntrackedVisits": 500,
    "trackedVisitsByDomain": [
      {
        "domain": "nytimes.com",
        "numSessions": 3,
        "visitsByReferrer": [
          {
            "referrerDomain": "google.com",
            "dayOfWeek": 1,
            "timeOfDay": 8,
            "pageCategory": 1,
            "numVisits": 10,
            "totalAttention": 500,
            "totalScroll": 400,
            "prevExposedCount": 3,
            "laterSharedCount": 1
          }
        ]
      }
    ]
  },

  "WebScience.Measurements.SocialMediaLinkSharing": {
    "linkSharesByPlatform": [
      {
        "platform": "facebook",
        "numUntrackedShares": 30,
        "trackedShares": [
          {
            "domain": "nytimes.com",
            "pageClassification": 0,
            "audience": "public",
            "source": "page",
            "visitReferrer": "google.com",
            "prevExposed": 1,
            "numShares": 5,
            "dayOfWeek": 2,
            "timeOfDay": 20
          },
          {
            "domain": "nytimes.com",
            "pageClassification": 1,
            "audience": "restricted",
            "source": "",
            "visitReferrer": "google.com",
            "prevExposed": 1,
            "numShares": 3,
            "dayOfWeek": 2,
            "timeOfDay": 20
          }
        ]
      },
      {
        "platform": "twitter",
        "numUntrackedShares": 10,
        "trackedShares": [
          {
            "domain": "nytimes.com",
            "pageClassification": 2,
            "visitReferrer": "google.com",
            "audience": "public",
            "source": "",
            "prevExposed": 0,
            "numShares": 2,
            "dayOfWeek": 2,
            "timeOfDay": 20
          }
        ]
      }
    ]
  },

  "WebScience.Measurements.LinkExposure": {
    "untrackedLinkExposures": {
      "1000": 10,
      "3000": 4,
      "5000": 4,
      "10000": 2
    },
    "linkExposures": [
      {
        "sourceDomain": "google.com",
        "destinationDomain": "nytimes.com",
        "dayOfWeek": 1,
        "timeOfDay": 4,
        "visThreshold": 3000,
        "numExposures": 10,
        "laterSharedCount": 3,
        "laterVisitedCount": 4
      },
      {
        "sourceDomain": "google.com",
        "destinationDomain": "nytimes.com",
        "dayOfWeek": 2,
        "timeOfDay": 8,
        "visThreshold": 1000,
        "numExposures": 3,
        "laterSharedCount": 3,
        "laterVisitedCount": 4
      }
    ]
  }
}
