=== SamPenrose/mozilla-pipeline-schemas/schemas/messaging-system/personalization-experiment/personalization-experiment.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "mozPipelineMetadata": {
    "bq_dataset_family": "messaging_system",
    "bq_table": "personalization_experiment_v1",
    "expiration_policy": {
      "delete_after_days": 180
    },
    "uri_scheme": "structured"
  },
  "properties": {
    "boolean_client_context_features": {
      "properties": {
        "dark_mode_active": {
          "type": "boolean"
        },
        "firefox_account_prefs_configured": {
          "type": "boolean"
        },
        "has_at_least_one_login_saved_in_the_browser": {
          "type": "boolean"
        },
        "has_at_least_one_self_installed_addon": {
          "type": "boolean"
        },
        "has_at_least_one_self_installed_popular_privacy_security_addon": {
          "type": "boolean"
        },
        "has_at_least_one_self_installed_theme": {
          "type": "boolean"
        },
        "has_firefox_as_default_browser": {
          "type": "boolean"
        },
        "has_more_than_12_active_ticks": {
          "type": "boolean"
        },
        "has_more_than_1_about_preferences_non_default_value_count": {
          "type": "boolean"
        },
        "has_more_than_5_bookmarks": {
          "type": "boolean"
        },
        "has_more_than_5_total_uri_count": {
          "type": "boolean"
        },
        "is_release_channel": {
          "type": "boolean"
        },
        "locale_is_de": {
          "type": "boolean"
        },
        "locale_is_en_us": {
          "type": "boolean"
        },
        "main_monitor_screen_width_gt_1280": {
          "type": "boolean"
        },
        "profile_more_than_60_days_old": {
          "type": "boolean"
        }
      },
      "required": [
        "has_firefox_as_default_browser",
        "has_more_than_12_active_ticks",
        "has_more_than_5_total_uri_count",
        "has_more_than_1_about_preferences_non_default_value_count",
        "has_at_least_one_self_installed_addon",
        "has_at_least_one_self_installed_popular_privacy_security_addon",
        "has_at_least_one_self_installed_theme",
        "dark_mode_active",
        "has_more_than_5_bookmarks",
        "has_at_least_one_login_saved_in_the_browser",
        "firefox_account_prefs_configured",
        "profile_more_than_60_days_old",
        "main_monitor_screen_width_gt_1280",
        "is_release_channel",
        "locale_is_en_us",
        "locale_is_de"
      ],
      "type": "object"
    },
    "client_context_features": {
      "properties": {
        "about_preferences_non_default_value_count": {
          "type": "number"
        },
        "active_ticks": {
          "type": "number"
        },
        "dark_mode_active": {
          "type": "boolean"
        },
        "firefox_account_prefs_configured": {
          "type": "boolean"
        },
        "has_firefox_as_default_browser": {
          "type": "boolean"
        },
        "locale": {
          "type": "string"
        },
        "logins_saved_in_the_browser_count": {
          "type": "number"
        },
        "main_monitor_screen_width": {
          "type": "number"
        },
        "profile_age_in_ms": {
          "type": "number"
        },
        "self_installed_addons_count": {
          "type": "number"
        },
        "self_installed_popular_privacy_security_addons_count": {
          "type": "number"
        },
        "self_installed_themes_count": {
          "type": "number"
        },
        "total_bookmarks_count": {
          "type": "number"
        },
        "total_uri_count": {
          "type": "number"
        },
        "update_channel": {
          "type": "string"
        }
      },
      "required": [
        "has_firefox_as_default_browser",
        "active_ticks",
        "total_uri_count",
        "about_preferences_non_default_value_count",
        "self_installed_addons_count",
        "self_installed_popular_privacy_security_addons_count",
        "self_installed_themes_count",
        "dark_mode_active",
        "total_bookmarks_count",
        "logins_saved_in_the_browser_count",
        "firefox_account_prefs_configured",
        "profile_age_in_ms",
        "main_monitor_screen_width",
        "update_channel",
        "locale"
      ],
      "type": "object"
    },
    "features_array_used_in_score_computation": {
      "items": {
        "type": "number"
      },
      "maxItems": 16,
      "minItems": 16,
      "type": "array"
    },
    "impression_id": {
      "type": "string"
    },
    "model_version": {
      "type": "number"
    },
    "study_addon_version": {
      "type": "string"
    },
    "study_variation": {
      "type": "string"
    }
  },
  "required": [
    "model_version",
    "study_variation",
    "study_addon_version",
    "client_context_features",
    "boolean_client_context_features",
    "features_array_used_in_score_computation"
  ],
  "title": "messaging-system-personalization-experiment-update",
  "type": "object"
}

=== SamPenrose/mozilla-pipeline-schemas/validation/messaging-system/personalization-experiment.1.event.pass.json
{
  "model_version": 20200102082643,
  "study_variation": "messaging-system-personalization-experiment-1-addon-treatment@mozilla.org",
  "study_addon_version": "1.0.0",
  "client_context_features": {
    "has_firefox_as_default_browser": true,
    "active_ticks": 5,
    "total_uri_count": 1,
    "about_preferences_non_default_value_count": 1,
    "self_installed_addons_count": 0,
    "self_installed_popular_privacy_security_addons_count": 0,
    "self_installed_themes_count": 0,
    "dark_mode_active": true,
    "total_bookmarks_count": 5,
    "logins_saved_in_the_browser_count": 0,
    "firefox_account_prefs_configured": false,
    "profile_age_in_ms": 26604,
    "main_monitor_screen_width": 1680,
    "update_channel": "aurora",
    "locale": "en-US"
  },
  "boolean_client_context_features": {
    "has_firefox_as_default_browser": true,
    "has_more_than_12_active_ticks": false,
    "has_more_than_5_total_uri_count": false,
    "has_more_than_1_about_preferences_non_default_value_count": false,
    "has_at_least_one_self_installed_addon": false,
    "has_at_least_one_self_installed_popular_privacy_security_addon": false,
    "has_at_least_one_self_installed_theme": false,
    "dark_mode_active": true,
    "has_more_than_5_bookmarks": false,
    "has_at_least_one_login_saved_in_the_browser": false,
    "firefox_account_prefs_configured": false,
    "profile_more_than_60_days_old": false,
    "main_monitor_screen_width_gt_1280": true,
    "is_release_channel": false,
    "locale_is_en_us": true,
    "locale_is_de": false
  },
  "features_array_used_in_score_computation": [
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    1,
    0,
    1,
    0
  ]
}
