=== SamPenrose/mozilla-pipeline-schemas/schemas/default-browser-agent/default-browser/default-browser.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "build_channel": {
      "type": "string"
    },
    "build_version": {
      "type": "string"
    },
    "client_id": {
      "description": "Deprecated; This field will never be sent",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "default_browser": {
      "description": "The current default browser",
      "type": "string"
    },
    "notification_action": {
      "description": "What action was taken by the user then the toast notification was displayed",
      "type": "string"
    },
    "notification_shown": {
      "description": "Whether the notification was shown, not shown, or resulted in an error",
      "type": "string"
    },
    "notification_type": {
      "description": "Whether the notification shown was the initial notification, or the followup",
      "type": "string"
    },
    "os_locale": {
      "description": "The current user's OS locale setting",
      "type": "string"
    },
    "os_version": {
      "description": "Windows version numnber in major.minor.build.UBR format (UBR is optional, only available on Win10)",
      "type": "string"
    },
    "previous_default_browser": {
      "description": "What the default browser was before it was changed to the current one",
      "type": "string"
    }
  },
  "required": [
    "build_channel",
    "build_version",
    "os_version",
    "os_locale"
  ],
  "title": "default-browser",
  "type": "object"
}

=== SamPenrose/mozilla-pipeline-schemas/validation/default-browser-agent/default-browser.1.sample_all_fields.pass.json
{
  "build_channel": "nightly",
  "build_version": "74.0a1",
  "os_version": "10.0.18363.592",
  "os_locale": "en-US",
  "default_browser": "firefox",
  "previous_default_browser": "edge",
  "client_id": "98D8A499-DBA0-4340-A058-64CF35986FFB",
  "notification_type": "initial",
  "notification_shown": "shown",
  "notification_action": "dismissed-by-timeout"
}
